#- pipeline.id: file-logstash-rabbitmq
#  path.config: "/usr/share/logstash/pipeline/logstash-rabbitmq.conf"
# - pipeline.id: logtstash-sfl-demo-petapet
#   path.config: "/usr/share/logstash/pipeline/logstash-sfl-demo.conf"
- pipeline.id: logstash-robot-shop
  path.config: "/usr/share/logstash/pipeline/logstash-robot-shop.conf"